name: Python format

on: [push, pull_request]

jobs:
  python-format:
    name: Enforce python format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@24.8.0
        with:
            version: "24.8.0"
            src: ./scripts
            # override options so that we can specify only specific files for now
            options: "--check --diff --include=.*addr2line.*"
